export default {
  language: 'English',
  Shanghai: 'Shanghai',
  Tokyo: 'Tokyo',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: 'Weibo',
  facebook: "Facebook",
  twitter: 'Twitter',
  blog: 'Blog',
  resume: 'Resume',
  frontend: "Front-end",
  kancolle: "KanColle",
  touhou: "TouHou",
  gup: "GuP",
}
