export default {
  language: '日本語',
  Shanghai: '上海',
  tokyo: '東京',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: 'Weibo',
  facebook: "Facebook",
  twitter: 'Twitter',
  blog: 'ブログ',
  resume: '履歴書',
  frontend: "フロントエンド",
  kancolle: "艦これ",
  touhou: "東方",
  gup: "ガルパン",
}
