export default {
  language: '简体中文',
  Shanghai: '上海',
  tokyo: '东京',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: '新浪微博',
  facebook: "Facebook",
  twitter: 'Twitter',
  blog: '博客',
  resume: '简历',
  frontend: "前端",
  kancolle: "舰娘",
  touhou: "东方",
  gup: "少战",
}
