export default {
  language: '正體中文',
  Shanghai: '上海',
  Tokyo: '東京',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: '新浪微博',
  facebook: "臉書",
  twitter: 'Twitter',
  blog: '部落格',
  resume: '簡歷',
  frontend: "前端",
  kancolle: "艦娘",
  touhou: "東方",
  gup: "少戰",
}
